[build]
  base = "Zerodha"  # Your frontend folder location
  publish = "dist"  # Where the build files are stored after running 'npm run build'
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
